/*********************************************************************
 *                                                                   *
 * MODULE NAME :  cnrez.h                			     *
 *                                                                   *
 * DESCRIPTION:                                                      *
 *                                                                   *
 *  Common definitions and function prototypes for CNREZ.EXE         *
 *                                                                   *
 *                                                                   *
 *********************************************************************/

#define CNR_SAMPLE       30
#define ID_RESOURCES     1
#define ICO_DOIT         20
#define IDM_ICON         100
#define IDM_NAME         110
#define IDM_TREE         120
#define IDM_DETAILS      130
#define IDM_TEXT         140
