# make makefile
#
# Tools used:
#  Compile::Resource Compiler
#  Compile::GNU C
#  Make: make
all : cnrez.exe

cnrez.exe : cnrez.obj cnrez.res cnrez.def
	gcc -Zomf cnrez.obj cnrez.res cnrez.def -o cnrez.exe
	wrc cnrez.res

cnrez.obj : cnrez.c cnrez.h
	gcc -Wall -Zomf -c -O2 cnrez.c -o cnrez.obj

cnrez.res : cnrez.rc 
	wrc -r cnrez.rc

clean :
	rm -rf *exe *res *obj *lib *dll *map
